"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Account(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    OPEN_TIMESTAMP_FIELD_NUMBER: _builtins.int
    CLOSE_TIMESTAMP_FIELD_NUMBER: _builtins.int
    CURRENCIES_FIELD_NUMBER: _builtins.int
    ACCOUNT_SWITCH_TO_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    display_name: _builtins.str
    account_switch_to: _builtins.str
    @_builtins.property
    def open_timestamp(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def close_timestamp(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def currencies(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        display_name: _builtins.str = ...,
        open_timestamp: _timestamp_pb2.Timestamp | None = ...,
        close_timestamp: _timestamp_pb2.Timestamp | None = ...,
        currencies: _abc.Iterable[_builtins.str] | None = ...,
        account_switch_to: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["close_timestamp", b"close_timestamp", "open_timestamp", b"open_timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["account_switch_to", b"account_switch_to", "close_timestamp", b"close_timestamp", "currencies", b"currencies", "display_name", b"display_name", "id", b"id", "open_timestamp", b"open_timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Account: _TypeAlias = Account  # noqa: Y015
