"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from protos import account_pb2 as _account_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class User(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACCOUNTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def accounts(self) -> _containers.RepeatedCompositeFieldContainer[_account_pb2.Account]: ...
    def __init__(
        self,
        *,
        accounts: _abc.Iterable[_account_pb2.Account] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accounts", b"accounts"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___User: _TypeAlias = User  # noqa: Y015
